language: ruby

rvm:
  - 1.9.3

env: TASKS=default

before_install:
  - sudo bash -c "echo deb http://badgerports.org precise main >> /etc/apt/sources.list"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E1FAD0C
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-devel

matrix:
  include:
    env: TASKS=spec
    before_install:
      - sudo apt-get update -qq
      - sudo apt-get install -qq mono-devel

install:
  - gem update --system
  - gem install rake albacore zip
  - mozroots --import --sync --quiet
  - mono ./src/packages/NuGet.CommandLine.2.8.2/tools/NuGet.exe restore ./src/LiteGuard.sln

script: rake $TASKS

notifications:
  email:
    - liteguard.ch@gmail.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fb4c45d35154322cdbd6
