language: ruby
rvm:
  - 1.9.3
install:
  - sudo apt-get install mono-complete
  - gem install rake
  - gem install albacore
  - chmod 744 tools/rakehelper/*.sh
script: rake clean build spec
notifications:
  email:
    - liteguardch@gmail.com
gemfile: Gemfile