version: '{build}'
image:
- Visual Studio 2017
- Ubuntu
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - /release-.*/
build_script:
- ps: ./build.ps1
- sh: ./build.sh
test: off
artifacts:
- path: ./**/*.nupkg
deploy: off
